language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release ./asn1sharp.Test/asn1sharp.Test.csproj

after_success:
  - bash deploy.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER $NUGET_ASN1_KEY $TRAVIS_TAG